// <auto-generated />
using System;
using Gastra.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gastra.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(GastraDbContext))]
    [Migration("20260923052133_AdicionaBloqueioPorTentativas")]
    partial class AdicionaBloqueioPorTentativas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gastra.Domain.Entidades.Alocacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Confirmada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("confirmada");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("GarcomId")
                        .HasColumnType("int")
                        .HasColumnName("garcom_id");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("periodo");

                    b.Property<int>("PracaId")
                        .HasColumnType("int")
                        .HasColumnName("praca_id");

                    b.HasKey("Id");

                    b.HasIndex("GarcomId");

                    b.HasIndex("PracaId");

                    b.HasIndex("Data", "Periodo", "GarcomId")
                        .IsUnique();

                    b.ToTable("alocacao", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.AvaliacaoAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int")
                        .HasColumnName("comanda_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(280)
                        .HasColumnType("varchar(280)")
                        .HasColumnName("comentario");

                    b.Property<DateTime>("DataHoraEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora_envio");

                    b.Property<int>("Nota")
                        .HasColumnType("int")
                        .HasColumnName("nota");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId")
                        .IsUnique();

                    b.ToTable("avaliacao_atendimento", null, t =>
                        {
                            t.HasCheckConstraint("CK_avaliacao_nota", "nota BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAcessoCliente")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("codigo_acesso_cliente");

                    b.Property<string>("Composicao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("composicao");

                    b.Property<bool>("ComposicaoAjustadaManualmente")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("composicao_ajustada_manualmente");

                    b.Property<DateTime>("DataHoraAbertura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora_abertura");

                    b.Property<DateTime?>("DataHoraFechamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora_fechamento");

                    b.Property<int>("GarcomId")
                        .HasColumnType("int")
                        .HasColumnName("garcom_id");

                    b.Property<int>("MesaId")
                        .HasColumnType("int")
                        .HasColumnName("mesa_id");

                    b.Property<int>("QuantidadePessoas")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_pessoas");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.Property<bool>("TaxaServicoRemovida")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("taxa_servico_removida");

                    b.HasKey("Id");

                    b.HasIndex("CodigoAcessoCliente")
                        .IsUnique();

                    b.HasIndex("GarcomId");

                    b.HasIndex("MesaId", "Status");

                    b.ToTable("comanda", null, t =>
                        {
                            t.HasCheckConstraint("CK_comanda_status_fechamento", "(status = 'Aberta' AND data_hora_fechamento IS NULL) OR (status = 'Fechada' AND data_hora_fechamento IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.ItemDoCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponivel");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("item_cardapio", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.ItemDoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int")
                        .HasColumnName("comanda_id");

                    b.Property<DateTime>("DataHoraRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora_registro");

                    b.Property<int>("ItemDoCardapioId")
                        .HasColumnType("int")
                        .HasColumnName("item_cardapio_id");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<decimal>("PrecoUnitarioNoMomento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_unitario_no_momento");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ItemDoCardapioId");

                    b.ToTable("item_pedido", null, t =>
                        {
                            t.HasCheckConstraint("CK_item_pedido_motivo_cancelamento", "(status = 'Cancelado' AND motivo_cancelamento IS NOT NULL) OR (status <> 'Cancelado' AND motivo_cancelamento IS NULL)");
                        });
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int")
                        .HasColumnName("capacidade");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numero");

                    b.Property<int>("PracaId")
                        .HasColumnType("int")
                        .HasColumnName("praca_id");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PracaId");

                    b.ToTable("mesa", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Praca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("QuantidadeGarcons")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_garcons");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("praca", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Promocao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativa");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("TipoDesconto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_desconto");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_desconto");

                    b.HasKey("Id");

                    b.HasIndex("Ativa", "DataInicio", "DataFim");

                    b.ToTable("promocao", null, t =>
                        {
                            t.HasCheckConstraint("CK_promocao_periodo_e_desconto", "data_fim >= data_inicio AND valor_desconto > 0 AND (tipo_desconto <> 'Percentual' OR valor_desconto < 100)");
                        });
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_hora_utc");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("detalhes");

                    b.Property<string>("Entidade")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entidade");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("evento");

                    b.Property<string>("IdCorrelacao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id_correlacao");

                    b.Property<int?>("IdEntidade")
                        .HasColumnType("int")
                        .HasColumnName("id_entidade");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip");

                    b.Property<string>("Papel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("papel");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("resultado");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraUtc");

                    b.HasIndex("UsuarioId", "DataHoraUtc");

                    b.ToTable("registro_auditoria", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.RestricaoAlimentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoria");

                    b.Property<int>("ComandaId")
                        .HasColumnType("int")
                        .HasColumnName("comanda_id");

                    b.Property<string>("ObservacaoLivre")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observacao_livre");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("restricao_alimentar", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("BloqueadaAte")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bloqueada_ate");

                    b.Property<Guid>("ChaveSessao")
                        .HasColumnType("char(36)")
                        .HasColumnName("chave_sessao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("papel");

                    b.Property<string>("SegredoTotp")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("segredo_totp");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("senha_hash");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("int")
                        .HasColumnName("tentativas_falhas");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Alocacao", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("GarcomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gastra.Domain.Entidades.Praca", null)
                        .WithMany()
                        .HasForeignKey("PracaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.AvaliacaoAtendimento", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Comanda", null)
                        .WithOne("Avaliacao")
                        .HasForeignKey("Gastra.Domain.Entidades.AvaliacaoAtendimento", "ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Comanda", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("GarcomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Gastra.Domain.Entidades.Mesa", null)
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.ItemDoCardapio", b =>
                {
                    b.OwnsMany("Gastra.Domain.Entidades.ItemCardapioFlag", "_flags", b1 =>
                        {
                            b1.Property<int>("ItemCardapioId")
                                .HasColumnType("int")
                                .HasColumnName("item_cardapio_id");

                            b1.Property<string>("Flag")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("flag");

                            b1.HasKey("ItemCardapioId", "Flag");

                            b1.ToTable("item_cardapio_flag", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ItemCardapioId");
                        });

                    b.Navigation("_flags");
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.ItemDoPedido", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Comanda", null)
                        .WithMany("Itens")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gastra.Domain.Entidades.ItemDoCardapio", null)
                        .WithMany()
                        .HasForeignKey("ItemDoCardapioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Mesa", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Praca", null)
                        .WithMany()
                        .HasForeignKey("PracaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Promocao", b =>
                {
                    b.OwnsMany("Gastra.Domain.Entidades.PromocaoItem", "_itens", b1 =>
                        {
                            b1.Property<int>("PromocaoId")
                                .HasColumnType("int")
                                .HasColumnName("promocao_id");

                            b1.Property<int>("ItemCardapioId")
                                .HasColumnType("int")
                                .HasColumnName("item_cardapio_id");

                            b1.HasKey("PromocaoId", "ItemCardapioId");

                            b1.HasIndex("ItemCardapioId");

                            b1.ToTable("promocao_item_cardapio", (string)null);

                            b1.HasOne("Gastra.Domain.Entidades.ItemDoCardapio", null)
                                .WithMany()
                                .HasForeignKey("ItemCardapioId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PromocaoId");
                        });

                    b.Navigation("_itens");
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.RestricaoAlimentar", b =>
                {
                    b.HasOne("Gastra.Domain.Entidades.Comanda", null)
                        .WithMany("Restricoes")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.Comanda", b =>
                {
                    b.Navigation("Avaliacao");

                    b.Navigation("Itens");

                    b.Navigation("Restricoes");
                });
#pragma warning restore 612, 618
        }
    }
}
