// <auto-generated />
using Gastra.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gastra.Infrastructure.DataAccess.Migrations
{
    [DbContext(typeof(GastraDbContext))]
    partial class GastraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gastra.Domain.Entidades.ItemDoCardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descricao");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("disponivel");

                    b.Property<string>("Imagem")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("imagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("item_cardapio", (string)null);
                });

            modelBuilder.Entity("Gastra.Domain.Entidades.ItemDoCardapio", b =>
                {
                    b.OwnsMany("Gastra.Domain.Entidades.ItemCardapioFlag", "_flags", b1 =>
                        {
                            b1.Property<int>("ItemCardapioId")
                                .HasColumnType("int")
                                .HasColumnName("item_cardapio_id");

                            b1.Property<string>("Flag")
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("flag");

                            b1.HasKey("ItemCardapioId", "Flag");

                            b1.ToTable("item_cardapio_flag", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ItemCardapioId");
                        });

                    b.Navigation("_flags");
                });
#pragma warning restore 612, 618
        }
    }
}
